### ISSUE TITLE
Possible typo in the book

### ISSUE THREAD

**Issue by paulc00** [PacktPublishing/Learn-React-with-TypeScript-2nd-Edition#3]
I wasn't sure where to report this but there seems to be a typo in the book in Chapter 4, section 'Using the callback Hook', step 7.

The second sentence in the paragraph starts with "Open React.tsx and add a React import statement". It looks like this should be "Open Reset.tsx and add a React import statement".

Thank you for an excellent book by the way. It has really good pacing and it builds up knowledge very efficiently. I'm enjoying working my way through it.

**Comment by carlrip** [comment]
Yep, there is a typo in Chapter 4, section 'Using the callback Hook', p137, step 7. As suggested, it should be `Reset.tsx` rather than `React.tsx`.

Step 7 on p137 should read as follows:

**7. We will now add React's `memo` function to try to prevent unnecessary re-renders. Open `Reset.tsx` and add a React import statement to import memo at the top of the file:**

This has been reported to the packt errata.
